### ISSUE TITLE
Events spanning midnight have incorrect End Date

### ISSUE THREAD

**Issue by neotsn** [iCalcreator/iCalcreator#95]
It would seem as of at least 2.29.29 through 2.30.5, an event created that starts at 9pm and ends at 6am the following day (as in the ics below) has its end-date miscalculated.

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//FireScope//NONSGML kigkonsult.se iCalcreator 2.29.29//
CALSCALE:GREGORIAN
METHOD:PUBLISH
UID:bc473209-5cca-4726-9cff-ed0e4360f96f
X-WR-CALNAME:Calendar
X-WR-CALDESC:Scheduled events.
X-WR-TIMEZONE:America/Chicago
BEGIN:VEVENT
UID:6176f48f65015c1a736187c9
DTSTAMP:20211025T181647Z
DESCRIPTION:Issue PRB36214\, #348830
DTSTART;TZID=America/Chicago:20211025T210000
DTEND;TZID=America/Chicago:20211026T060000
RRULE:FREQ=DAILY;INTERVAL=1;WKST=SU
SUMMARY:Test Over Night MW
END:VEVENT
END:VCALENDAR
```

In this case, the date Oct 25, 2021 @ 9pm America/Chicago through Oct 26, 2021 @ 6am America/Chicago comes back with an end date of Oct 25, 2021 @ 6am America/Chicago.

In the code below, I'm attempting to siphon off the relevant parts of the wrapper class I built to handle interactions with the library to show how we arrive at the occurrences, but the final line of the code indicates the direct request for the X-prop that comes back with the wrong string date, relative to the input from the ICS string. 

```php
// $icsString = '... the above string...';
$timezone = new DateTimeZone('America/Chicago');
// From the start date of the occurrence displayed on the calendar
$startDate = new DateTime('@1635213600', $timezone);
// 1 Year in the future from start date, for sanity
$endDate = new DateTime('@1666749600', $timezone);

// Initialize a vcalendar object from the ics string
$calendar = (new Vcalendar())->parse($icsString);
$occurrences = [];

// Iterate through the years, months, days, events arrays to compile the events as determined by the library
if ($years = $calendar->selectComponents($startDate, $endDate, null, null, null, null, Vcalendar::VEVENT)) {
    foreach ($years as $months) {
        foreach ($months as $days) {
            foreach ($days as $events) {
                foreach ($events as $event) {
                    $occurrences[] = $event;
                }
            }
        }
    }
}

// Extract the first event found
$occurrence = reset($occurrences);

// Read off the DTEND
error_log(json_encode($occurrence->getXprop(Vcalendar::X_CURRENT_DTEND)));
```

Output becomes:
```
["X-CURRENT-DTEND","2021-10-25 06:00:00 America\\/Chicago"]
```

And for what it's worth, a PHP Unit test around the functionality with the provided inputs above, gives the result:
```
Overnight End Date is calculated correctly
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2021-10-26 06:00:00 America/Chicago'
+'2021-10-25 06:00:00 America/Chicago'
```

I'm sorry that I cannot upgrade past the releases that support php 5.6, this is an issue I'm actively working on correcting in this legacy product, so any help you can give for this version branch is appreciated.

**Comment by iCalcreator** [comment]
Working on it, same in 2.40 also...

**Comment by iCalcreator** [comment]
Fixed in 2.40.4

To change in 2.30.5 SelectFactory.php :

row 1033-1036 from
        elseif(( $rStart->format( $YMDn ) < $rEnd->format( $YMDn )) &&
            ( 0 == $endHis[0] ) && ( 0 == $endHis[1] ) && ( 0 == $endHis[2] )) {
            $rStart->setTime( 24, 0, 0 ); // end exactly at midnight
        }
to
        elseif( $rStart->format( $YMDn ) < $rEnd->format( $YMDn )) {
            if( ( 0 === $endHis[0] ) && ( 0 === $endHis[1] ) && ( 0 === $endHis[2] )) {
                $rStart->setTime( 24, 0 ); // end exactly at midnight  // 24:00:00
            }
            else {
                $rStart->setTime( 23, 59, 59 ); // break at midnight, cont next day  // 23:59:59
            }
        }

row 470-480 from
                                    self::setDurationEndTime(
                                        $rStart,
                                        $rEnd,
                                        $cnt,
                                        $occurenceDays,
                                        $endHis
                                    );
                                    $component3->setXprop(
                                        $propName,
                                        $rStart->format( $compEnd->dateFormat )
                                    );
to
                                    $rWdate = $rStart->getClone();
                                    self::setDurationEndTime(
                                        $rWdate,
                                        $rEnd,
                                        $cnt,
                                        $occurenceDays,
                                        $endHis
                                    );
                                    $component3->setXprop(
                                        $propName,
                                        $rWdate->format( $compEnd->dateFormat )
                                    );

row  318-328 from
                                self::setDurationEndTime(
                                    $rStart,
                                    $rEnd,
                                    $cnt,
                                    $occurenceDays,
                                    $endHis
                                );
                                $component2->setXprop(
                                    $propName,
                                    $rStart->format( $compEnd->dateFormat )
                                );

to
                                $rWdate = $rStart->getClone();
                                self::setDurationEndTime(
                                    $rWdate,
                                    $rEnd,
                                    $cnt,
                                    $occurenceDays,
                                    $endHis
                                );
                                $component2->setXprop(
                                    $propName,
                                    $rWdate->format( $compEnd->dateFormat )
                                );

**Comment by neotsn** [comment]
Thanks so much for your help. Do you recommend I fork this, and tag my own release to carry on the 2.30.x series?

**Comment by neotsn** [comment]
In the meantime, I have made the patch changes directly to the vendor file for the version v2.30.5, and then updated all my unit test dates & unix times to represent the year 2030 instead of 2021 (as this area of my code deals with fetching future occurrences for a calendar), and yet the unit test still fails with the same issue:
```
There was 1 failure:

---------
1) FsCalendarTest: Over night event
 Test  tests/unit/FsCalendarTest.php:testOverNightEvent
Overnight End Date is calculated correctly
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2030-10-26 06:00:00 America/Chicago'
+'2030-10-25 23:59:59 America/Chicago'
```
I wish I could offer some suggestions for how to fix the issue, but there is simply too much shorthand in the variables to contribute anything reasonable from my end.

The only thing I really notice is that all of the changes indicated are related to the Start Date of occurrences, but the issue is with calculating the End Date of a future occurrence.

**Comment by iCalcreator** [comment]
New release 2.30.6 with the fix.

Note, as for now, each occurrence of the over-night-event has a span over two days : 
first day 21:00:00 to 23:59:59, second day 00:00:00 to 06:00:00
and (for all but first) the occurrence  first day will overwrite the previous occurrence second day.
Working on it...

**Comment by iCalcreator** [comment]
Fixed in iCalcreator 2.30.7 and 2.40.6

**Comment by neotsn** [comment]
I'm sorry, but my unit test still returns the same incorrect result:

```
There was 1 failure:

---------
1) FsCalendarTest: Over night event
 Test  tests/unit/FsCalendarTest.php:testOverNightEvent
Overnight End Date is calculated correctly
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2030-10-26 06:00:00 America/Chicago'
+'2030-10-25 23:59:59 America/Chicago'
```
I went digging into the code to see if I can offer any help, and I have come up with some changes that yield the expected results for the issue, and that also do not break existing tests/functionality in use (at least for me; you'll want to verify these changes on your own).

In `src/Util/SelectFactory.php` on Lines **488-493** change from:
```php
list( $xY, $xM, $xD ) = self::getArrayYMDkeys( $rStart );
if( ! isset( $result[$xY][$xM][$xD][$compUID] )) {
    $result[$xY][$xM][$xD][$compUID] = [];
}
$result[$xY][$xM][$xD][$compUID][] = clone $component3;     // copy to output
$rStart->add( $INTERVAL_P1D );
```
to
```php
list( $xY, $xM, $xD ) = self::getArrayYMDkeys( $rStart );
$result[$xY][$xM][$xD][$compUID] = clone $component3;     // copy to output
break;
```
This breaks the while-loop once it writes the component to the results for the day indicated on occurrences beyond the initial one. As this is in a loop, and with the change to use an array of components, a new event is occurrence is generated on every iteration, causing multi-day events to trigger another version of itself that starts on the next day that runs through the original finish date (due to the next change...)

---

On Lines **475-486**, change from:
```php
$rWdate = $rStart->getClone();
self::setDurationEndTime(
    $rWdate,
    $rEnd,
    $cnt,
    $occurenceDays,
    $endHis
);
$component3->setXprop(
    $propName,
    $rWdate->format( $compEnd->dateFormat )
)
```
to 
```php
$rWdate = $rStart->getClone();
self::setDurationEndTime(
    $rWdate,
    $rEnd,
    $cnt,
    $occurenceDays,
    $endHis
);
$component3->setXprop(
    $propName,
    $rEnd->format( $compEnd->dateFormat )
)
```
This uses the actual End Date instead of a modified start date clone to terminate the occurrence, which means once we've gotten to this point in the loop the previous patch's `break` statement becomes necessary to cease work.

---

On Lines **442-450**, change from:
```php
if( $rStart->format( $YMDn ) <
    $fcnStart->format( $YMDn )) { // date before dtstart
    $rStart->add( $INTERVAL_P1D ); // cycle rstart to dtstart
    $rStart->setTime( 0, 0 );
    continue;
}
elseif( 2 == $cnt ) {
    $rStart->setTime( 0, 0 );
}
```
to
```php
if( $rStart->format( $YMDn ) <
    $fcnStart->format( $YMDn )) { // date before dtstart
    $rStart->add( $INTERVAL_P1D ); // cycle rstart to dtstart
    continue;
}
```
No need to reset the time to 0. Every time we go through the loop, nothing changes about the start time, it's always incrementing by a full day, so it maintains the hour/minute/second from the original start date.

---

On Lines **330-335**, change from: 
```php
list( $xY, $xM, $xD ) = self::getArrayYMDkeys( $rStart );
if( ! isset( $result[$xY][$xM][$xD][$compUID] )) {
    $result[$xY][$xM][$xD][$compUID] = [];
}
$result[$xY][$xM][$xD][$compUID][] = clone $component2;   // copy to output
$rStart->add( $INTERVAL_P1D );
```
to
```php
list( $xY, $xM, $xD ) = self::getArrayYMDkeys( $rStart );
$result[$xY][$xM][$xD][$compUID] = clone $component2;   // copy to output
break;
```
Same as the "write component, break loop" patch from the first code snippet, but this one is for the first occurrence.

On Lines **317-328**, change from:
```php
$rWdate = $rStart->getClone();
self::setDurationEndTime(
    $rWdate,
    $rEnd,
    $cnt,
    $occurenceDays,
    $endHis
);
$component2->setXprop(
    $propName,
    $rWdate->format( $compEnd->dateFormat )
);
```
to 
```php
$rWdate = $rStart->getClone();
self::setDurationEndTime(
    $rWdate,
    $rEnd,
    $cnt,
    $occurenceDays,
    $endHis
);
$component2->setXprop(
    $propName,
    $rEnd->format( $compEnd->dateFormat )
);
```
Same as the End Date for occurrences, but this is for the first occurrence.

---

These "patches" are just to get the code to a "working" state for this issue. It will require some additional knowledge that I don't have about whether the data at play is impacted for the other "else" statements in these loops (e.g., `// !$flat && !$split,` else statement) as I was unable to trigger those with my various use-cases.

I hope this helps.

**Comment by iCalcreator** [comment]
Try the new 2.30.8 release

**Comment by neotsn** [comment]
My apologies, but inline clone syntax like `(clone $compStart )` is not supported in php 5.6. Changing the 4 occurrences in the file, I still get the same failed unit tests, and with the added trouble that only Monthly events render in the calendar because the start dates of the expected recurrences cannot be verified as legit occurrences returned from the plugin.

```
There was 1 failure:

---------
1) FsCalendarTest: Over night event
 Test  tests/unit/FsCalendarTest.php:testOverNightEvent
Overnight End Date is calculated correctly
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2030-10-26 06:00:00 America/Chicago'
+'2030-10-25 23:59:59 America/Chicago'
```

**Comment by iCalcreator** [comment]
Fixed in the new 3.30.9 / 2.40.7 releases.

Nice testcase, tricky... ;)

Note, alter your test-script
from
```php
$startDate = new DateTime('@1635213600', $timezone ); // set date in UTC, ignore timezone
```
to
```
$startDate = new DateTime('@1635213600' );
$startDate->setTimezone( $timezone ); // set  'America/Chicago'
```

Also in top of script to verify dates
```php
echo 'START startDate: ' . $startDate->format( 'YmdHs e' ) . ' endDate: ' . $endDate->format( 'YmdHs e' ) . PHP_EOL;
```

If you add 
```php
            $ymd = $year . '-' .
                str_pad((string) $month, 2, '0', STR_PAD_LEFT ) . '-' .
                str_pad((string) $day, 2, '0', STR_PAD_LEFT ) . ' ';
            foreach( $events as $event ) {
                while( $xProp = $event->getXprop()) {
                    echo $ymd . str_pad( $xProp[0], 18 ) . $xProp[1] . PHP_EOL;
                } // end while
                echo ' ' . PHP_EOL;
            } // end foreach
```
in the loop,
will produce a nice sequence of all x-props in date order.

**Comment by neotsn** [comment]
Hey sorry for the late reply, I have been on vacation for US Thanksgiving holiday last week. Also thank you for the details, I can now see why we are getting different results.

As mentioned in an earlier reply, I changed my test to address "future occurrences" by updating the year to 2030 for the same month/day/hour in the original time zone. In this case, I have been using a string version of the date, like so for the unit test:

```php
// Set in the before-method
$mockTimezone = new DateTimeZone('America/Chicago');
// Set in the actual test method
$startDate = new DateTime('2030-10-25 21:00:00 America/Chicago', $mockTimezone);
$endDate = new DateTime('2030-10-26 06:00:00 America/Chicago', $mockTimezone);
```
As such, my ICS String resembles this with the 2030 dates:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Calendar//NONSGML kigkonsult.se 2.30.9//
CALSCALE:GREGORIAN
METHOD:PUBLISH
UID:bc473209-5cca-4726-9cff-ed0e4360f96f
X-WR-CALNAME:Calendar
X-WR-CALDESC:Scheduled events.
X-WR-TIMEZONE:America/Chicago
BEGIN:VEVENT
UID:6176f48f65015c1a736187c9
DTSTAMP:20301025T181647Z
DESCRIPTION:Testing OverNight Events
DTSTART;TZID=America/Chicago:20301025T210000
DTEND;TZID=America/Chicago:20301026T060000
RRULE:FREQ=DAILY;INTERVAL=1;WKST=SU
SUMMARY:Test Over Night MW
END:VEVENT
END:VCALENDAR
```
Here is a more complete version of the original test code sequence, extracting the iCalcreator plugin portions of my code as called in the unit test method.

```php
$icsString = ' /* the above ics string, flattened with /r/n */';
$vCalendar = (new Vcalendar())->parse($icsString);

$mockTimezone = new DateTimeZone('America/Chicago');
$startDate = new DateTime('2030-10-25 21:00:00 America/Chicago', $mockTimezone);
$endDate = new DateTime('2030-10-26 06:00:00 America/Chicago', $mockTimezone);

// This is redundant, because it's test code and prod code extracted...also some helper methods removed for clarity
$calendarTimeZone = new DateTimeZone($vCalendar->getXprop(Vcalendar::X_WR_TIMEZONE)[1] ?:  date_default_timezone_get());

$startDate->setTimezone($calendarTimeZone);
$endDate->setTimezone($calendarTimeZone);

// Skipping code that checks the start date is > time() and that there is 
// an event within a year from the start date for sanity is no End Date provided
// because it calls the same "get future occurrences" code with a year-end-date
// instead of the provided end date

// Ensure that the vEvent stored in vCalendar is up-to-date with changes
// potentially made elsewhere via the wrapper class, but not in this example
$vEvent = null;
while ($event = $vCalendar->getComponent(Vcalendar::VEVENT)) {
    $vEvent = $event;

    // if there isn't a sequence (or the sequence is 0) then we're on the main event
    if (!$event->getSequence()) {
        break;
    }
}

// set an empty event if none exists
$vEvent = $vEvent ?: $vCalendar->newVevent();
// vCalendar->getComponent returns clones, so we need to insert
$vCalendar->replaceComponent($vEvent);

// gather Vevents from the Vcalendar
if ($years = $vCalendar->selectComponents($startDate, $endDate, null, null, null, null, Vcalendar::VEVENT)) {
    foreach ($years as $months) {
        foreach ($months as $days) {
            foreach ($days as $events) {
                foreach ($events as $event) {
                    $occurrences[] = $event;
                }
            }
        }
    }
}

// take the first one from the stack
$occurrence = reset($occurrences);

// Make sure it resolves to start at the same time as requested
$result = false;
if($occurrence && (new DateTime($occurrence->getXprop(Vcalendar::X_CURRENT_DTSTART)[1])) == $startDate) {
    $result = $occurrence;
}

// Back to the Test Code...
$endString = $occurrence->getXprop(Vcalendar::X_CURRENT_DTEND)[1];
self::assertEquals('2030-10-26 06:00:00 America/Chicago', $endString, 'Overnight End Date is calculated correctly');
```
At this point, I get the error that *future events* are not correctly identified in the unit test (I am not testing past events, those are handled through immutable snapshots of date/time occurrences stored separately from the ICS string):
```
1) FsCalendarTest: Over night event
 Test  tests/unit/FsCalendarTest.php:testOverNightEvent
Overnight End Date is calculated correctly
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2030-10-26 06:00:00 America/Chicago'
+'2030-10-25 23:59:59 America/Chicago'
```
I have tried to extract enough working code here to allow you to reproduce the issue, so I hope I didn't miss anything. However, I did provide earlier the changes to the code that address the issue without impacting any of the other areas of functionality that I have tests for. Were these insufficient for your usage? Or did they introduce other problems?

Thanks again for your help in solving this.

**Comment by iCalcreator** [comment]
Given your new ics-string and the start/enddates, I got dates and first (day) event xProps like this
```
START startDate : 2030-10-25 21:00:00 America/Chicago
      endDate   : 2030-10-26 06:00:00 America/Chicago

X-OCCURENCE       day 1 of 2
X-CURRENT-DTSTART 2030-10-25 21:00:00 America/Chicago
X-CURRENT-DTEND   2030-10-25 23:59:59 America/Chicago
```
looks ok for me

**Comment by neotsn** [comment]
Ok, then this is where the issue lies: expectation of what is "ok". We've been using this plugin for several years, but it seems it wasn't until 2.29.29 (or shortly before) that there was a "breaking change" to make multi-day events split into multiple "occurrence" objects representing the duration contained with in a 24hr period relative to the time zone of the calendar.

This creates a problem for applications when a single vEvent occurrence object is expected to span its full duration with a pair of DateTime objects for the start/end dates & times, regardless of whether that events spans a calendar date in one time zone or another. This is especially the case when the event itself is created for 1 time zone, while the user is viewing it in another time zone.

If this functionality is allowed to persist, a calendar application that allows the user to create 2 events using 2 different timezones (say for "sever maintenance over night from 11p to 2a in London" and the same but for "America/Chicago"), a viewer of the calendar who renders it in any other time zone will see 4 events on the calendar because the object has been divided up incorrectly.

Do you have any reference materials available that lead to the reason for this change in functionality?

I am interested to learn the challenge that required this solution, but I am also trying to figure out how this should work in code for my own application if the events are split up by each day they overlap. This behavior is not seen when interacting with any calendar applications (e.g., Outlook, Google, or Apple).

Again, I did offer fixes to address the issue by not using an array of vEvents to represent a single occurrence, and instead just using the start and end dates where the start date is the expected iteration start time, and the end date is just the duration from that start date. If I can understand the reason for this change, then I can determine whether I need to code around this unexpected behavior, or fork the repository and apply those patches myself.

**Comment by iCalcreator** [comment]
There is no change in functionality.
If you do not want to 'split' events on days,
set the last arg (split) in the method selectComponents to false
like
```
$vCalendar->selectComponents(
    $startDate,
    $endDate,
    null,
    null,
    null,
    null,
    Vcalendar::VEVENT,
    false,    // default false
    true,     // default true
    false     // default true
);
```

Note, the 'first' event (on dtstart Ymd) do not have any xprops.

There is an endDate issue, may ignore the 'His' part, working on it.

**Comment by neotsn** [comment]
Thank you for this tip! I am now trying to work with the `false` split flag and getting better results...but you're right: the first in the series does not have any xprops, and this is the part that is failing for me now.

When you say you're "working on it," are you working on fixing the first event's xprops, or only on the endDate issue?

**Comment by iCalcreator** [comment]
New releases 2.30.10 / 2.40.10, fixed both issues

**Comment by neotsn** [comment]
Praise be! All unit tests have passed... thank you so much for your help with this, and your hard work on this library. It's the only one comprehensive enough for my usage in the land of PHP.
